window.NGACHI_PROJECTS = [
  {
    "id": "heart-of-gold",
    "title": "Heart of Gold — The Feminine Shop",
    "category": "AI PRODUCT AD · THE FEMININE SHOP",
    "description": "A cinematic jewelry ad showcasing a gold heart belly ring through close-up detail, warm lighting and gentle camera movement. Created by Ngachi.ai for The Feminine Shop, this vertical product film brings the jewelry into focus with a premium, intimate feel.",
    "format": "13 seconds · Vertical · 1080 × 1920",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/heart-of-gold.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/heart-of-gold.jpg",
    "alt": "Gold crystal heart belly ring on warm wood for The Feminine Shop",
    "group": "Jewelry",
    "duration": 13,
    "selected": true,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/heart-of-gold-preview.mp4",
    "focus": "Product detail · Warm lighting · Jewelry",
    "searchTerms": ""
  },
  {
    "id": "yummy-yoghie",
    "title": "Yummy Yoghie",
    "category": "AI COMMERCIAL · FOOD & BEVERAGE",
    "description": "Branded product story built for social",
    "format": "64 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/yummy-yoghie.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/yummy-yoghie.jpg",
    "alt": "Yummy Yoghie campaign still",
    "group": "Food",
    "duration": 64,
    "selected": true,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/yummy-yoghie-preview.mp4",
    "focus": "Product storytelling · Food & beverage",
    "searchTerms": ""
  },
  {
    "id": "vanilla-dessert",
    "title": "Vanilla, Elevated",
    "category": "PRODUCT FILM · FOOD",
    "description": "Sensory cinematography with rich texture detail",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/vanilla-dessert.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/vanilla-dessert-thumbnail.jpg",
    "alt": "AI Food Commercial thumbnail featuring vanilla ice cream, chocolate sauce, strawberries and a cookie",
    "group": "Food",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/vanilla-dessert-preview.mp4",
    "focus": "Food · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "heart-belly-ring",
    "title": "Heart, in Motion",
    "category": "AI PRODUCT FILM · BODY JEWELLERY",
    "description": "A heart belly ring transformed into a clean, confidence-led vertical product ad for The Feminine Shop",
    "format": "8 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/heart-belly-ring.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/heart-belly-ring.webp",
    "alt": "Gold heart belly ring product ad for The Feminine Shop",
    "group": "Jewelry",
    "duration": 8,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/heart-belly-ring-preview.mp4",
    "focus": "Body Jewellery · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "suya-commercial",
    "title": "Suya, Reimagined",
    "category": "AI FOOD COMMERCIAL · CULINARY",
    "description": "Smoke, spice and street-food energy shaped into a premium vertical commercial",
    "format": "10 seconds · Vertical · 1080 × 1920",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/suya-commercial.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/suya-commercial.jpg",
    "alt": "Grilled Nigerian suya skewers over glowing charcoal",
    "group": "Food",
    "duration": 10,
    "selected": true,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/suya-commercial-preview.mp4",
    "focus": "Smoke & texture · Nigerian food",
    "searchTerms": ""
  },
  {
    "id": "luxury-transport",
    "title": "Book Your SUV",
    "category": "AI COMMERCIAL · LUXURY TRANSPORT",
    "description": "Story-led airport and lifestyle campaign",
    "format": "60 seconds · Vertical · 540 × 960",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/luxury-transport.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/luxury-transport.jpg",
    "alt": "Luxury chauffeur campaign still",
    "group": "Lifestyle",
    "duration": 60,
    "selected": true,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/luxury-transport-preview.mp4",
    "focus": "Lifestyle narrative · Luxury transport",
    "searchTerms": ""
  },
  {
    "id": "beauty-clinic",
    "title": "Confidence, Reframed",
    "category": "BRAND FILM · BEAUTY",
    "description": "Premium beauty and wellness storytelling",
    "format": "32 seconds · Vertical · 540 × 960",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/beauty-clinic.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/beauty-clinic.jpg",
    "alt": "Beauty clinic campaign still",
    "group": "Beauty",
    "duration": 32,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/beauty-clinic-preview.mp4",
    "focus": "Beauty · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "wellness-ugc",
    "title": "MindBiotic",
    "category": "AI UGC · WELLNESS",
    "description": "Native-feeling product demonstration",
    "format": "37 seconds · Vertical · 540 × 960",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/wellness-ugc.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/wellness-ugc.jpg",
    "alt": "Wellness UGC campaign still",
    "group": "UGC",
    "duration": 37,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/wellness-ugc-preview.mp4",
    "focus": "Wellness · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "pet-tech",
    "title": "Smarter Mealtimes",
    "category": "PRODUCT FILM · PET TECH",
    "description": "Cinematic product feature showcase",
    "format": "66 seconds · Vertical · 540 × 960",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/pet-tech.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/pet-tech.jpg",
    "alt": "Smart pet feeder campaign still",
    "group": "Pets",
    "duration": 66,
    "selected": true,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/pet-tech-preview.mp4",
    "focus": "Cat-led storytelling · Product demonstration",
    "searchTerms": "cats cat feeder pet"
  },
  {
    "id": "fashion-social",
    "title": "Saturday Shopping",
    "category": "SOCIAL CONTENT · E-COMMERCE",
    "description": "Fast, relatable conversion-led creative",
    "format": "30 seconds · Vertical · 540 × 960",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/fashion-social.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/fashion-social.jpg",
    "alt": "Fashion e-commerce social campaign still",
    "group": "Fashion",
    "duration": 30,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/fashion-social-preview.mp4",
    "focus": "E-Commerce · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "shawarma-built-to-crave",
    "title": "Shawarma, Built to Crave",
    "category": "AI FOOD COMMERCIAL · RESTAURANT",
    "description": "An appetite-led vertical commercial following fresh ingredients, grilled chicken and the final cut",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/shawarma-built-to-crave.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/shawarma-built-to-crave.png",
    "alt": "Chicken shawarma food commercial with grilled chicken, fresh vegetables and toasted flatbread",
    "group": "Food",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/shawarma-built-to-crave-preview.mp4",
    "focus": "Restaurant · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "dream-home",
    "title": "Dream Home",
    "category": "AI COMMERCIAL · REAL ESTATE",
    "description": "Aspiration-led residential property showcase",
    "format": "30 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/dream-home.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/dream-home.jpg",
    "alt": "Modern dream home campaign still",
    "group": "Property",
    "duration": 30,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/dream-home-preview.mp4",
    "focus": "Real Estate · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "itel-power-tank",
    "title": "Itel Power Tank",
    "category": "PRODUCT FILM · SOLAR ENERGY",
    "description": "Product-led energy solution concept",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/itel-power-tank.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/itel-power-tank.jpg",
    "alt": "Itel Power Tank solar campaign still",
    "group": "Technology",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/itel-power-tank-preview.mp4",
    "focus": "Solar Energy · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "luxury-pet-care",
    "title": "Luxury Pet Care",
    "category": "BRAND FILM · PET CARE",
    "description": "Premium clinic storytelling with human warmth",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/luxury-pet-care.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/luxury-pet-care.jpg",
    "alt": "Luxury pet care clinic campaign still",
    "group": "Pets",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/luxury-pet-care-preview.mp4",
    "focus": "Pet Care · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "modern-skyline",
    "title": "Built for Tomorrow",
    "category": "CONCEPT FILM · PROPERTY",
    "description": "Modern development and skyline visualisation",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/modern-skyline.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/modern-skyline.jpg",
    "alt": "Modern property development campaign still",
    "group": "Property",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/modern-skyline-preview.mp4",
    "focus": "Property · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "property-arrival",
    "title": "The Arrival",
    "category": "HOSPITALITY FILM · PROPERTY",
    "description": "Guest experience and destination storytelling",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/property-arrival.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/property-arrival.jpg",
    "alt": "Travelers arriving at a property campaign still",
    "group": "Property",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/property-arrival-preview.mp4",
    "focus": "Property · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "saas-commercial",
    "title": "SaaS, Made Cinematic",
    "category": "AI COMMERCIAL · TECHNOLOGY",
    "description": "Software storytelling translated into human stakes",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/saas-commercial.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/saas-commercial.jpg",
    "alt": "Cinematic SaaS campaign still",
    "group": "Technology",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/saas-commercial-preview.mp4",
    "focus": "Technology · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "ai-workflows",
    "title": "Work Smarter",
    "category": "AI COMMERCIAL · BUSINESS",
    "description": "AI workflow storytelling for modern teams",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/ai-workflows.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/ai-workflows.jpg",
    "alt": "AI workflow business campaign still",
    "group": "Technology",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/ai-workflows-preview.mp4",
    "focus": "Business · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "jollof-from-scratch",
    "title": "Jollof, From Scratch",
    "category": "AI FOOD FILM · CULINARY",
    "description": "A sensory food story from fresh peppers to the final plate",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/jollof-from-scratch.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/jollof-from-scratch.jpg",
    "alt": "Nigerian jollof rice and grilled chicken campaign still",
    "group": "Food",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/jollof-from-scratch-preview.mp4",
    "focus": "Culinary · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "sketch-to-couture",
    "title": "From Sketch to Couture",
    "category": "AI FASHION COMMERCIAL · LUXURY FASHION",
    "description": "A cinematic fashion story following an original gown sketch through fabric, tailoring and the final couture reveal",
    "format": "10 seconds · Vertical · 720 × 1280",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/sketch-to-couture.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/sketch-to-couture.png",
    "alt": "Emerald couture gown shown beside its original fashion sketch",
    "group": "Fashion",
    "duration": 10,
    "selected": true,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/sketch-to-couture-preview.mp4",
    "focus": "Visual continuity · Fashion craftsmanship",
    "searchTerms": ""
  },
  {
    "id": "nigerian-breakfast-reimagined",
    "title": "Nigerian Breakfast, Reimagined",
    "category": "AI FOOD COMMERCIAL · RESTAURANT",
    "description": "A 10-second vertical AI food commercial turning akara, pap, eggs and bread into a warm, appetite-led restaurant campaign designed for Reels, TikTok and social ads.",
    "format": "10 seconds · Vertical · 1080 × 1920",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/nigerian-breakfast-reimagined.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/nigerian-breakfast-reimagined.webp",
    "alt": "Cinematic Nigerian breakfast with akara, pap, eggs and bread",
    "group": "Food",
    "duration": 10,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/nigerian-breakfast-reimagined-preview.mp4",
    "focus": "Restaurant · Visual storytelling",
    "searchTerms": ""
  },
  {
    "id": "ai-explained-simply",
    "title": "AI, Explained Simply",
    "category": "AI EXPLAINER · EDUCATIONAL CONTENT",
    "description": "A self-initiated educational explainer introducing AI through everyday examples, pattern learning and image classification, with a reminder to check AI outputs. Ngachi.ai handled the concept, script, Google Flow visuals and CapCut editing.",
    "format": "28 seconds · Landscape · 854 × 480",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/ai-explained-simply.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/ai-explained-simply.png",
    "alt": "AI, Made Simple thumbnail with a Black female presenter, laptop, music-note and envelope icons",
    "group": "Technology",
    "duration": 28,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/ai-explained-simply-preview.mp4",
    "focus": "Plain-language script · Supporting visuals · Educational storytelling",
    "searchTerms": "AI artificial intelligence explainer educational presenter Google Flow CapCut"
  },
  {
    "id": "creative-intelligence-os",
    "title": "The Creative Intelligence OS",
    "category": "AI COMMERCIAL · CREATIVE DIRECTION",
    "description": "A continuity-led Ngachi.ai brand film showing how direction turns AI frames into one coherent story",
    "format": "31 seconds · Vertical · 1080 × 1920",
    "video": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/creative-intelligence-os.mp4",
    "poster": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/creative-intelligence-os.jpg",
    "alt": "Creative director reviewing a consistent AI product campaign",
    "group": "Technology",
    "duration": 31,
    "selected": false,
    "preview": "https://ngachiai-portfolio.adangamnwachukwu.chatgpt.site/assets/creative-intelligence-os-preview.mp4",
    "focus": "Creative Direction · Visual storytelling",
    "searchTerms": ""
  }
];
